/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListFrame.java
 *
 * Created on Jun 17, 2009, 4:35:58 PM
 */
package winemanager;

import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Luis
 */
public class ListFrame extends javax.swing.JFrame {

    private static BasicTableModel listModel;
    private TableRowSorter sorter;
    private List<RowSorter.SortKey> sortKeys;

    /** Creates new form ListFrame */
    public ListFrame() {
        initComponents();
        initializeTable();
        jFormattedTextField1.requestFocusInWindow();
        this.setIconImage(Utils.getFrameIcon());
        setUIText();
    }
    
    private void setUIText(){
        lblFilter.setText(WineMainFrame.strings.getString("lblFilter"));
        this.setTitle(WineMainFrame.strings.getString("listFrame_title"));
    }

    public static BasicTableModel getListModel() {
        return listModel;
    }

    public JTable getTable() {
        return jTable1;
    }

    private void initializeTable() {
        listModel = new BasicTableModel(WineMainFrame.getVinos());
        sorter = new TableRowSorter<TableModel>(listModel);
        sorter.setComparator(5, new MyComparator());
        sorter.setComparator(6, new MyComparator());
        sorter.setComparator(7, new MyComparator());
        sorter.setComparator(9, new MyComparator());
        jTable1.setRowSorter(sorter);
        jTable1.setModel(listModel);

        sortKeys = new ArrayList<RowSorter.SortKey>();
        sortKeys.add(new RowSorter.SortKey(1, SortOrder.ASCENDING));
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);

        TableColumn tc1 = jTable1.getColumnModel().getColumn(0);
        tc1.setPreferredWidth(200);
        TableColumn tc2 = jTable1.getColumnModel().getColumn(1);
        tc2.setPreferredWidth(125);
        TableColumn tc3 = jTable1.getColumnModel().getColumn(2);
        tc3.setPreferredWidth(125);
        TableColumn tc4 = jTable1.getColumnModel().getColumn(4);
        tc4.setPreferredWidth(100);
        TableColumn tc5 = jTable1.getColumnModel().getColumn(3);
        tc5.setPreferredWidth(75);
        for (int i = 5; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(75);
        }

        jTable1.setDefaultRenderer(Double.class, new CurrencyRenderer());
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int viewRow = jTable1.getSelectedRow();
                    if (viewRow != -1) {
                        int modelRow = jTable1.convertRowIndexToModel(viewRow);
                        Vino v = listModel.getWineAt(modelRow);
                        EditWineFrame ewf = new EditWineFrame(v,modelRow);
                        ewf.setVisible(true);
                    }
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblFilter = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de vinos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        lblFilter.setText("Expresion para filtrar");

        txtFilter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtFilterCaretUpdate(evt);
            }
        });

        jLabel2.setText("UPC");

        jFormattedTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jFormattedTextField1CaretUpdate(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFilter)
                                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(40, 40, 40)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtFilterCaretUpdate
        String expr = txtFilter.getText();
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + expr));
        sorter.setSortKeys(sortKeys);
    }//GEN-LAST:event_txtFilterCaretUpdate

    private void jFormattedTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jFormattedTextField1CaretUpdate
        boolean wineFound = false;
        jLabel3.setText("");
        int length = evt.getDot();
        class ResetField implements Runnable {

            public void run() {
                jFormattedTextField1.setText("");
            }
        }
        if (length == 12 || length == 13) {
            for (int i=0; i<WineMainFrame.getVinos().size(); i++) {
                Vino v = WineMainFrame.getVinos().get(i);
                if (v.getUPC().equals(jFormattedTextField1.getText())) {
                    wineFound = true;
                    int modelRow = jTable1.convertRowIndexToView(i);
                    jTable1.getSelectionModel().setSelectionInterval(modelRow,modelRow);
                    Rectangle rect = jTable1.getCellRect(modelRow, 0, true);
                    jTable1.scrollRectToVisible(rect);
                    EditWineFrame ewf = new EditWineFrame(v,modelRow);
                    ewf.setVisible(true);
                    SwingUtilities.invokeLater(new ResetField());
                    jFormattedTextField1.requestFocusInWindow();
                }
            }
            if (!wineFound) {
                jLabel3.setText(WineMainFrame.strings.getString("msg_incorrectUPC"));
            }
        }
    }//GEN-LAST:event_jFormattedTextField1CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
