/*
 * StatisticsFrame.java
 *
 * Created on June 13, 2007, 8:27 AM
 */
package winemanager;

import java.awt.*;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.HashMap;

/**
 *
 * @author Luiso
 */
public class StatisticsFrame extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form StatisticsFrame
     */
    public StatisticsFrame() {
        initComponents();
        this.setIconImage(Utils.getFrameIcon());
        int cantidadTotal = 0;
        BigDecimal dineroTotal = new BigDecimal("0");
        MyList paises = new MyList();
        MyList regiones = new MyList();
        MyList anos = new MyList();
        for (Vino v : WineMainFrame.getVinos()) {
            int cantidad = v.getQuantity();
            cantidadTotal += cantidad;
            BigDecimal dinero = new BigDecimal(String.valueOf(v.getTotalAmount()));
            dineroTotal = dineroTotal.add(dinero);
            paises.myAdd(v.getCountry(), v.getQuantity());
            if (v.getRegion() == null) {
                regiones.myAdd("", v.getQuantity());
            } else {
                String region = v.getRegion().trim();
                regiones.myAdd(region, v.getQuantity());
            }
            anos.myAdd(Integer.toString(v.getYear()), v.getQuantity());
        }

        int max = 0;
        String maxName = "";
        int maxBottles = 0;
        for (Pair p : paises) {
            if (p.getQuantity() > max) {
                max = p.getQuantity();
                maxName = (String) p.getName();
                maxBottles = p.getBottles();
            }
        }
        jTextField3.setText(maxName + " (" + max + " vinos y " + maxBottles + " botellas)");

        max = 0;
        maxName = "";
        for (Pair p : anos) {
            if (p.getQuantity() > max) {
                max = p.getQuantity();
                maxName = (String) p.getName();
                maxBottles = p.getBottles();
            }
        }
        jTextField4.setText(maxName + " (" + max + " vinos y " + maxBottles + " botellas)");

        max = 0;
        maxName = "";
        for (Pair p : regiones) {
            if (!p.getName().equals("")) {
                if (p.getQuantity() > max) {
                    max = p.getQuantity();
                    maxName = (String) p.getName();
                    maxBottles = p.getBottles();
                }
            }
        }
        jTextField5.setText(maxName + " (" + max + " vinos y " + maxBottles + " botellas)");

        jTextField1.setText(String.valueOf(cantidadTotal));
        NumberFormat nf = NumberFormat.getCurrencyInstance();
        String s = nf.format(dineroTotal.floatValue());
        jTextField2.setText(s);
        
        setUIText();
    }
    
    private void setUIText(){
        btnDetails.setText(WineMainFrame.strings.getString("btnDetails"));
        btnPrint.setText(WineMainFrame.strings.getString("btnPrint"));
        lblMostCountry.setText(WineMainFrame.strings.getString("lblMostCountry"));
        lblMostRegion.setText(WineMainFrame.strings.getString("lblMostRegion"));
        lblMostYear.setText(WineMainFrame.strings.getString("lblMostYear"));
        lblTotalValue.setText(WineMainFrame.strings.getString("lblTotalValue"));
        lblTotalBottles.setText(WineMainFrame.strings.getString("lblTotalBottles"));
        this.setTitle(WineMainFrame.strings.getString("statisticsFrame_title"));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalBottles = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lblMostCountry = new javax.swing.JLabel();
        lblMostYear = new javax.swing.JLabel();
        lblMostRegion = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadisticas");
        setResizable(false);

        lblTotalBottles.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalBottles.setText("El número total de botellas es:");

        lblTotalValue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalValue.setText("El valor total de las botellas es:");

        jTextField1.setEditable(false);
        jTextField1.setBorder(null);

        jTextField2.setEditable(false);
        jTextField2.setBorder(null);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lblMostCountry.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMostCountry.setText("El pais con mas botellas es:");

        lblMostYear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMostYear.setText("El año con mas botellas es:");

        lblMostRegion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMostRegion.setText("La region con mas botellas es:");

        jTextField3.setEditable(false);
        jTextField3.setBorder(null);

        jTextField4.setEditable(false);
        jTextField4.setBorder(null);

        jTextField5.setEditable(false);
        jTextField5.setBorder(null);

        btnPrint.setText("Imprimir");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnDetails.setText("Detalles");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotalBottles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblMostYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMostRegion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblMostCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBottles)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalValue)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMostCountry)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMostYear)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMostRegion)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnPrint)
                    .addComponent(btnDetails))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-482)/2, (screenSize.height-304)/2, 482, 304);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        PrinterJob printJob = PrinterJob.getPrinterJob();
        printJob.setPrintable(this);
        if (printJob.printDialog()) {
            try {
                printJob.print();
            } catch (PrinterException pe) {
                System.out.println(WineMainFrame.strings.getString("wineMainFrame_errorPrinting") + "\n" + pe.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        DetailedStatistics ds = new DetailedStatistics();
        ds.setLocationRelativeTo(null);
        ds.setVisible(true);
    }//GEN-LAST:event_btnDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StatisticsFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPrint;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblMostCountry;
    private javax.swing.JLabel lblMostRegion;
    private javax.swing.JLabel lblMostYear;
    private javax.swing.JLabel lblTotalBottles;
    private javax.swing.JLabel lblTotalValue;
    // End of variables declaration//GEN-END:variables

    public int print(Graphics graphics, PageFormat pageFormat, int i) throws PrinterException {
        if (i == 0) {
            Graphics2D graphics2D = (Graphics2D) graphics;
            //graphics2D.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            double imageablex = pageFormat.getImageableWidth()/2;
            double imageabley = pageFormat.getImageableHeight()/2;
            Rectangle te = this.getBounds();            
            double printHeight = imageabley - (te.height/2);
            double printWidth = imageablex - (te.width/2);
            graphics2D.translate(printWidth, printHeight);
            HashMap<RenderingHints.Key, Object> hm = new HashMap<RenderingHints.Key, Object>();
            hm.put(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_OFF);
            hm.put(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_SPEED);
            hm.put(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_SPEED);
            hm.put(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_SPEED);
            //graphics2D.setRenderingHints(hm);
            this.printAll(graphics2D);
            return (PAGE_EXISTS);
        } else {
            return (NO_SUCH_PAGE);
        }
    }
}
